eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10002/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: server2
server:
  port: 10001
